#!/usr/bin/env python3
"""Merge one-frame-per-file Img2Lcd C arrays into a header for h2bin.py."""

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path


COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\r\n]*", re.DOTALL)
DECL_RE = re.compile(
    r"(?:\bstatic\s+)?(?:\bconst\s+)?"
    r"(?:unsigned\s+char|uint8_t)\s+"
    r"(?:(?:const|code|PROGMEM)\s+)*"
    r"(?P<name>[A-Za-z_]\w*)\s*\[[^\]]*\]\s*"
    r"(?:(?:code|PROGMEM)\s*)*=\s*\{",
    re.MULTILINE,
)
BYTE_RE = re.compile(r"0[xX][0-9a-fA-F]+|\b\d+\b")
VALID_INITIALIZER_RE = re.compile(
    r"^(?:\s|,|0[xX][0-9a-fA-F]+|\d+)*$", re.DOTALL
)


class MergeError(ValueError):
    """An input file is not a valid one-frame Img2Lcd source."""


def natural_key(name: str):
    """Sort frame2.c before frame10.c."""
    return [int(part) if part.isdigit() else part.casefold()
            for part in re.split(r"(\d+)", name)]


def _find_closing_brace(text: str, start: int, path: Path) -> int:
    end = text.find("}", start)
    if end < 0:
        raise MergeError(f"{path.name}: 数组缺少闭合的 '}}'")
    return end


def parse_single_array(path: Path) -> tuple[str, bytes]:
    """Return the only byte array in an Img2Lcd C file."""
    text = path.read_text(encoding="utf-8", errors="replace")
    text = COMMENT_RE.sub("", text)
    matches = list(DECL_RE.finditer(text))
    if not matches:
        raise MergeError(f"{path.name}: 没有找到受支持的字节数组")
    if len(matches) != 1:
        raise MergeError(f"{path.name}: 找到 {len(matches)} 个数组，每个 .c 必须只有一帧")

    match = matches[0]
    end = _find_closing_brace(text, match.end(), path)
    initializer = text[match.end():end]
    if not VALID_INITIALIZER_RE.fullmatch(initializer):
        raise MergeError(f"{path.name}: 数组中含有数字和逗号以外的内容")

    values = []
    for token in BYTE_RE.findall(initializer):
        value = int(token, 0)
        if not 0 <= value <= 0xFF:
            raise MergeError(f"{path.name}: 字节 {token} 超出 0~255")
        values.append(value)
    if not values:
        raise MergeError(f"{path.name}: 数组没有任何字节")
    return match.group("name"), bytes(values)


def _write_frame(stream, index: int, source: Path, data: bytes) -> None:
    stream.write(f"/* frame {index:06d}: {source.name} */\n")
    stream.write(f"static const unsigned char BMP{index:06d}[] = {{\n")
    for offset in range(0, len(data), 16):
        row = data[offset:offset + 16]
        stream.write("    " + ", ".join(f"0x{value:02X}" for value in row) + ",\n")
    stream.write("};\n\n")


def merge_directory(input_dir: Path, output_header: Path) -> tuple[int, int]:
    input_dir = input_dir.resolve()
    if not input_dir.is_dir():
        raise MergeError(f"找不到输入目录: {input_dir}")

    sources = sorted(
        (path for path in input_dir.iterdir()
         if path.is_file() and path.suffix.casefold() == ".c"),
        key=lambda path: natural_key(path.name),
    )
    if not sources:
        raise MergeError(f"{input_dir} 中没有 .c 文件")

    output_header = output_header.resolve()
    if not output_header.parent.is_dir():
        raise MergeError(f"输出目录不存在: {output_header.parent}")

    temporary_name = None
    frame_bytes = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", newline="\n", delete=False,
            dir=output_header.parent, prefix=output_header.name + ".",
            suffix=".tmp",
        ) as stream:
            temporary_name = stream.name
            stream.write("#ifndef OVID_MERGED_FRAMES_H\n")
            stream.write("#define OVID_MERGED_FRAMES_H\n\n")
            stream.write("/* Generated by tools/merge_img2lcd.py. */\n\n")

            for index, source in enumerate(sources, 1):
                _, data = parse_single_array(source)
                if frame_bytes is None:
                    frame_bytes = len(data)
                elif len(data) != frame_bytes:
                    raise MergeError(
                        f"{source.name}: {len(data)} B，与首帧 {frame_bytes} B 不一致"
                    )
                _write_frame(stream, index, source, data)

            stream.write("#endif /* OVID_MERGED_FRAMES_H */\n")

        os.replace(temporary_name, output_header)
        temporary_name = None
    finally:
        if temporary_name:
            Path(temporary_name).unlink(missing_ok=True)

    return len(sources), int(frame_bytes or 0)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="按自然文件名顺序合并 Img2Lcd 单帧 .c 文件"
    )
    parser.add_argument("input_dir", help="包含一帧一个 .c 的目录")
    parser.add_argument("output_header", help="输出 .h 文件")
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    try:
        count, frame_bytes = merge_directory(
            Path(args.input_dir), Path(args.output_header)
        )
    except (MergeError, OSError) as exc:
        print(f"错误：{exc}", file=sys.stderr)
        return 1

    print(f"已写出 {args.output_header}")
    print(f"  {count} 帧  每帧 {frame_bytes} B  数组 BMP000001~BMP{count:06d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
