#ifndef APP_VERSION_H
#define APP_VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 3
#define APP_VERSION_PATCH 2
#define APP_VERSION_PRERELEASE "beta.1"
#define APP_VERSION_STRING "1.3.2-beta.1"
#define APP_VERSION_DISPLAY "FW V1.3.2-b1"

#endif
